apiVersion: v1alpha1
kind: CatalogItemInstance
metadata:
  name: gitops-two-tier-web
spec:
  display_name: gitops-two-tier-web
  catalog_item_id: flpath-4894-two-tier-web
  user_values:
    - resource: backend
      path: metadata.name
      value: gitops-backend
    - resource: backend
      path: image.reference
      value: docker.io/library/nginx:alpine
    - resource: frontend
      path: metadata.name
      value: gitops-frontend
    - resource: frontend
      path: image.reference
      value: docker.io/library/httpd:alpine
